name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.10.0
          driver-opts: image=moby/buildkit:v0.11.0
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: C:\Users\Moisht\Documents\Script Docker-Terraform\DockerCICD
          build-args: |
            ARG1=value1
            ARG2=value2
          file: C:\Users\Moisht\Documents\Script Docker-Terraform\DockerCICD\Dockerfile
          outputs: type=image, name=index.docker.io/${{ secrets.ContainerUsername }}/tes1t:${{ github.sha }}
  
  push:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.ContainerUsername }}
          password: ${{ secrets.ContainerPassword }}
      - name: Push container image to registry
        uses: docker/build-push-action@v2
        with:
          images: 'index.docker.io/${{ secrets.ContainerUsername }}/tes1t:${{ github.sha}}'
          push: true
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'moseietdockercicd'
          slot-name: 'production'
          publish-profile: ${{ secrets.PublishProfile }}
          images: 'index.docker.io/${{ secrets.ContainerUsername }}/tes1t:${{ github.sha}}'
