name: Build and deploy container app to Azure Web App - moseiet/dockercicdnginx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.ContainerUsername }}
          password: ${{ secrets.ContainerPassword }}

      - name: Build and push container image to registry
        run: |
          docker build C:\Users\Moisht\Documents\Script Docker-Terraform\DockerCICD -t index.docker.io/${{ secrets.ContainerUsername }}/tes1t:${{ github.sha }}
          docker push index.docker.io/${{ secrets.ContainerUsername }}/tes1t:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deply-to-webapp.outpunts.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deply-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'moseietdockercicd'
          slot-name: 'production'
          publish-profile: ${{ secrets.PublishProfile }}
          images: 'index.docker.io/${{ secrets.ContainerUsername }}/dockercicdnginx:${{ github.sha}}'
