name: Build and deploy container app to Azure Web App - moseiet/dockercicdnginx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.ContainerUsername }}
          password: ${{ secrets.ContainerPassword }}
      
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: moseiet/tes1t:latest
        env:
          DOCKER_BUILDKIT: 0
          # Disables Docker Buildx and uses the default Docker engine
        shell: bash --noprofile --norc -eo pipefail {0}
        # Required for the `--progress plain` flag to work on Windows-based runners
        # If using a Linux-based runner, remove this line
      
      - name: Push Docker image manifest
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          manifest: true
          tags: moseiet/tes1t:latest
        env:
          DOCKER_BUILDKIT: 0
          # Disables Docker Buildx and uses the default Docker engine
        shell: bash --noprofile --norc -eo pipefail {0}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'moseietdockercicd'
          slot-name: 'production'
          publish-profile: ${{ secrets.PublishProfile }}
          images: 'index.docker.io/${{ secrets.ContainerUsername }}/dockercicdnginx:${{ github.sha }}'
