name: Build and deploy container app to Azure Web App - moseiet/dockercicdnginx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://hub.docker.com/repository/docker/moseiet/dockercicdnginx/general
          username: ${{ secrets.ContainerUsername }}
          password: ${{ secrets.ContainerPassword }}

      - name: Build and push container image to registry
        uses: kdocker/build-push-action@v2
        with:
          context: C:\Users\Moisht\Documents\Script Docker-Terraform\DockerCICD
          push: true
          tags: index.docker.io/${{ secrets.ContainerUsername }}/dockercicdnginx:${{ github.sha }}
          file: C:\Users\Moisht\Documents\Script Docker-Terraform\DockerCICD\Dockerfile
