name: Build and deploy container app to Azure Web App - moseiet/dockercicdnginx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.ContainerUsername }}
          password: ${{ secrets.ContainerPassword }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.ContainerUsername }}/dockercicdnginx:${{ github.sha }}
          file: ./Dockerfile
